# Generated by Django 5.1.7 on 2025-04-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
