# Generated by Django 5.1.7 on 2025-06-16 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasepartinquiry',
            name='store_inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_part_inquiries', to='bititec.storeinquiry'),
        ),
    ]
