# Generated by Django 5.1.7 on 2025-04-26 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0002_customuser_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseAccInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bititec.accessory')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_inquiries', to='bititec.leasecontract')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LeasePartInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_inquiries', to='bititec.leasecontract')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bititec.part')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
