# Generated by Django 5.1.7 on 2025-04-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0003_leaseaccinquiry_leasepartinquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phonenumber',
            field=models.PositiveIntegerField(verbose_name='phone number'),
        ),
    ]
