# Generated by Django 5.1.7 on 2025-06-20 08:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0003_quotation_quotationitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessorytype',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='machinetype',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='parttype',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='accessorytype',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='accessorytype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessorytype',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='accessory_types/'),
        ),
        migrations.AddField(
            model_name='accessorytype',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='accessory_types/'),
        ),
        migrations.AddField(
            model_name='accessorytype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='machinetype',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='machinetype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinetype',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='machine_types/'),
        ),
        migrations.AddField(
            model_name='machinetype',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='machine_types/'),
        ),
        migrations.AddField(
            model_name='machinetype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='parttype',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='parttype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parttype',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='part_types/'),
        ),
        migrations.AddField(
            model_name='parttype',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='part_types/'),
        ),
        migrations.AddField(
            model_name='parttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='accessorytype',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accessorytype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='machinetype',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='machinetype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parttype',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parttype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
