# Generated by Django 5.1.7 on 2025-06-20 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0004_alter_accessorytype_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessory',
            old_name='description',
            new_name='conditon_description',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='description',
            new_name='condition_description',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='description',
            new_name='condition_description',
        ),
    ]
