# Generated by Django 5.1.7 on 2025-05-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0004_alter_customuser_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='intial_quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='intial_quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
