# Generated by Django 5.1.7 on 2025-05-02 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0005_accessory_intial_quantity_part_intial_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='bititec.part'),
        ),
    ]
