# Generated by Django 5.1.7 on 2025-06-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0005_rename_description_accessory_conditon_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number'),
        ),
    ]
