# Generated by Django 5.1.7 on 2025-07-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0006_alter_customuser_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='action_taken',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='call',
            name='parts_required',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='call',
            name='parts_used',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
    ]
