# Generated by Django 5.1.7 on 2025-05-03 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0006_alter_saleitem_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='bititec.accessory'),
        ),
    ]
