# Generated by Django 5.1.7 on 2025-07-15 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0008_alter_call_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasecontract',
            name='technician',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['Technician', 'Technician Manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leases', to=settings.AUTH_USER_MODEL),
        ),
    ]
