# Generated by Django 5.1.7 on 2025-05-06 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0008_alter_saleitem_accessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_type',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Lease', 'Lease')], default='Sale', max_length=20),
        ),
        migrations.AddField(
            model_name='delivery',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='bititec.leasecontract'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='bititec.sale'),
        ),
    ]
