# Generated by Django 5.1.7 on 2025-05-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0009_delivery_delivery_type_delivery_lease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='local_client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('Internal', 'Internal'), ('Local', 'Local')], default='Internal', max_length=20),
        ),
    ]
