# Generated by Django 5.1.7 on 2025-05-08 07:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0010_sale_local_client_name_sale_sale_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('meter_reading', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='bititec.leasecontract')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bititec.machine')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('lease', 'month')},
            },
        ),
    ]
