# Generated by Django 5.1.7 on 2025-05-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0011_meterreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='add_vat',
            field=models.BooleanField(default=False),
        ),
    ]
