# Generated by Django 5.1.7 on 2025-08-11 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0011_transfer_transferitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='source_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_accessories', to='bititec.transfer'),
        ),
        migrations.AddField(
            model_name='machine',
            name='source_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_machines', to='bititec.transfer'),
        ),
        migrations.AddField(
            model_name='part',
            name='source_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_parts', to='bititec.transfer'),
        ),
    ]
