# Generated by Django 5.1.7 on 2025-08-12 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0012_accessory_source_transfer_machine_source_transfer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessory',
            old_name='conditon_description',
            new_name='condition_description',
        ),
    ]
