# Generated by Django 5.1.7 on 2025-05-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0013_alter_sale_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='custom_item',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('client_name', 'client_location')},
        ),
    ]
