# Generated by Django 5.1.7 on 2025-08-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0013_rename_conditon_description_accessory_condition_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Maintenance', 'Maintenance'), ('Leased', 'Leased'), ('Out of Stock', 'Out of Stock'), ('Sold', 'Sold')], max_length=20),
        ),
    ]
