# Generated by Django 5.1.7 on 2025-05-20 07:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0014_saleitem_custom_item_alter_client_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCallToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('service_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='bititec.call')),
            ],
        ),
    ]
