# Generated by Django 5.1.7 on 2025-08-18 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0014_alter_machine_machine_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='current_machine',
            field=models.ForeignKey(blank=True, help_text='Machine this part is currently installed in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_parts', to='bititec.machine'),
        ),
        migrations.AddField(
            model_name='part',
            name='installed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='origin_machine',
            field=models.ForeignKey(blank=True, help_text='Machine this part was originally removed from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donated_parts', to='bititec.machine'),
        ),
        migrations.AddField(
            model_name='part',
            name='removed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
