# Generated by Django 5.1.7 on 2025-05-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0015_servicecalltoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='client_verification',
            field=models.BooleanField(default=False),
        ),
    ]
