# Generated by Django 5.1.7 on 2025-08-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0015_part_current_machine_part_installed_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leasepartinquiry',
            old_name='amount',
            new_name='unit_amount',
        ),
        migrations.RemoveField(
            model_name='leasepartinquiry',
            name='vat',
        ),
        migrations.AddField(
            model_name='leasepartinquiry',
            name='apply_vat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leasepartinquiry',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=7, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leasepartinquiry',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=78, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leasepartinquiry',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='leasepartinquiry',
            name='vat_rate',
            field=models.DecimalField(decimal_places=4, default=0.16, max_digits=5),
        ),
        migrations.AddField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='vat_rate',
            field=models.DecimalField(decimal_places=4, default=0.16, max_digits=5),
        ),
        migrations.AddField(
            model_name='sale',
            name='vat_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=98, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitem',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
