# Generated by Django 5.1.7 on 2025-08-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0016_rename_amount_leasepartinquiry_unit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='service_type',
            field=models.CharField(choices=[('Network Support', 'Network Support'), ('Hardware & Software Support', 'Hardware & Software Support'), ('Installation', 'Installation')], default='Hardware & Software Support', max_length=50),
        ),
    ]
