# Generated by Django 5.1.7 on 2025-08-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0017_call_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='service_type',
            field=models.CharField(choices=[('Network Support', 'Network Support'), ('Hardware & Software Support', 'Hardware & Software Support'), ('Installation', 'Installation'), ('Scheduled Maintenance', 'Scheduled Maintenance')], default='Hardware & Software Support', max_length=50),
        ),
    ]
