# Generated by Django 5.1.7 on 2025-05-22 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0017_clientmachine_storeinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='client_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='call',
            name='client_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bititec.clientmachine'),
        ),
        migrations.AddField(
            model_name='call',
            name='client_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='call',
            name='technician_manager_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='call',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bititec.client'),
        ),
        migrations.AlterField(
            model_name='call',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bititec.machine'),
        ),
    ]
