# Generated by Django 5.1.7 on 2025-08-25 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0018_alter_call_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='additional_permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Additional permissions beyond role-based access'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='permission_granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='permission_granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='permission_reason',
            field=models.TextField(blank=True, help_text='Reason for granting additional permissions'),
        ),
        migrations.CreateModel(
            name='PermissionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_key', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('GRANTED', 'Granted'), ('REVOKED', 'Revoked')], max_length=20)),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
