# Generated by Django 5.1.7 on 2025-05-23 18:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0018_call_client_location_call_client_machine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinquiry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
