# Generated by Django 5.1.7 on 2025-05-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0019_alter_storeinquiry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinquiry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
