# Generated by Django 5.1.7 on 2025-08-25 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0019_customuser_additional_permissions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='permission_granted_at',
            new_name='keys_granted_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='additional_permissions',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='permission_granted_by',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='permission_reason',
        ),
        migrations.AddField(
            model_name='customuser',
            name='keys',
            field=models.JSONField(blank=True, default=dict, help_text="Permission keys with access levels: {'inventory': ['read', 'create'], 'sales': ['read', 'update', 'delete']}"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='keys_granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='keys_reason',
            field=models.TextField(blank=True, help_text='Reason for granting keys'),
        ),
        migrations.CreateModel(
            name='KeyAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('actions', models.JSONField(default=list)),
                ('action_type', models.CharField(choices=[('GRANTED', 'Granted'), ('REVOKED', 'Revoked'), ('MODIFIED', 'Modified')], max_length=20)),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='PermissionAudit',
        ),
    ]
