# Generated by Django 5.1.7 on 2025-08-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0020_rename_permission_granted_at_customuser_keys_granted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='keys',
            field=models.JSONField(blank=True, default=dict, help_text="Permission keys with access levels: {'inventory': ['read', 'create'], 'sales': ['read', 'update', 'delete']}", null=True),
        ),
    ]
