# Generated by Django 5.1.7 on 2025-05-23 19:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0020_alter_storeinquiry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinquiry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
