# Generated by Django 5.1.7 on 2025-05-26 19:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0021_alter_storeinquiry_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeinquiry',
            options={'ordering': ['-requested_at']},
        ),
        migrations.AlterField(
            model_name='leaseaccinquiry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leasepartinquiry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
