# Generated by Django 5.1.7 on 2025-08-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0021_alter_customuser_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='lpo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='delivery',
            name='lpo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sale',
            name='lpo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
