# Generated by Django 5.1.7 on 2025-09-05 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0022_call_lpo_delivery_lpo_sale_lpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasecontract',
            name='account_handler',
            field=models.ForeignKey(blank=True, help_text='User responsible for managing this lease account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_leases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='technician',
            field=models.ForeignKey(blank=True, help_text='Technician assigned for maintenance/support', limit_choices_to={'role__in': ['Technician', 'Technician Manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leases', to=settings.AUTH_USER_MODEL),
        ),
    ]
