# Generated by Django 5.1.7 on 2025-05-26 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0022_alter_storeinquiry_options_alter_leaseaccinquiry_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasepartinquiry',
            name='store_inquiry',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='lease_part_inquiries', to='bititec.storeinquiry'),
            preserve_default=False,
        ),
    ]
