# Generated by Django 5.1.7 on 2025-05-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0023_leasepartinquiry_store_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='walk_in_machine_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='call',
            name='walk_in_machine_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='call',
            name='walk_in_serial_no',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
