# Generated by Django 5.1.7 on 2025-09-08 10:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0023_leasecontract_account_handler_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('supplier', models.CharField(max_length=255)),
                ('supplier_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_by_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=16, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('include_vat', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved by Sales Manager', 'Approved by Sales Manager'), ('Rejected by Sales Manager', 'Rejected by Sales Manager'), ('Approved by Director', 'Approved by Director'), ('Rejected by Director', 'Rejected by Director'), ('Ordered', 'Ordered'), ('Cancelled', 'Cancelled')], default='Draft', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_pdf', models.FileField(blank=True, null=True, upload_to='purchase_orders/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('verified_by_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_director_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('verified_by_sales_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_sales_purchase_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('MachineType', 'Machine Type'), ('PartType', 'Part Type'), ('AccessoryType', 'Accessory Type'), ('Custom', 'Custom Item')], max_length=20)),
                ('item_id', models.UUIDField(blank=True, null=True)),
                ('item_name', models.CharField(max_length=255)),
                ('item_brand', models.CharField(blank=True, max_length=255)),
                ('item_code', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bititec.purchaseorder')),
            ],
        ),
    ]
