# Generated by Django 5.1.7 on 2025-06-01 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0024_call_walk_in_machine_name_call_walk_in_machine_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='store_inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bititec.storeinquiry'),
        ),
    ]
