# Generated by Django 5.1.7 on 2025-09-08 14:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0024_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='store_inquiry',
        ),
        migrations.RemoveField(
            model_name='leasepartinquiry',
            name='store_inquiry',
        ),
        migrations.RenameField(
            model_name='leaseaccinquiry',
            old_name='amount',
            new_name='unit_amount',
        ),
        migrations.RemoveField(
            model_name='leaseaccinquiry',
            name='vat',
        ),
        migrations.AddField(
            model_name='leaseaccinquiry',
            name='apply_vat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaseaccinquiry',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=3.0, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaseaccinquiry',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=3.0, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaseaccinquiry',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='leaseaccinquiry',
            name='vat_rate',
            field=models.DecimalField(decimal_places=4, default=0.16, max_digits=5),
        ),
        migrations.CreateModel(
            name='StoreAccessoryInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acc_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('add_vat', models.BooleanField(default=False)),
                ('is_issued', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Issued', 'Issued'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_accessory_inquiries', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('service_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_store_inquiries', to='bititec.call')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddField(
            model_name='leaseaccinquiry',
            name='store_acc_inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_acc_inquiries', to='bititec.storeaccessoryinquiry'),
        ),
        migrations.AddField(
            model_name='sale',
            name='store_acc_inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bititec.storeaccessoryinquiry'),
        ),
        migrations.CreateModel(
            name='StorePartInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('add_vat', models.BooleanField(default=False)),
                ('is_issued', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Issued', 'Issued'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_part_inquiries', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('service_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_store_inquiries', to='bititec.call')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddField(
            model_name='leasepartinquiry',
            name='store_part_inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_part_inquiries', to='bititec.storepartinquiry'),
        ),
        migrations.AddField(
            model_name='sale',
            name='store_part_inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bititec.storepartinquiry'),
        ),
        migrations.DeleteModel(
            name='StoreInquiry',
        ),
    ]
