# Generated by Django 5.1.7 on 2025-06-01 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0025_saleitem_store_inquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='store_inquiry',
        ),
        migrations.AddField(
            model_name='sale',
            name='store_inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bititec.storeinquiry'),
        ),
    ]
