# Generated by Django 5.1.7 on 2025-09-09 08:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0025_remove_sale_store_inquiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseaccinquiry',
            name='vat_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.16'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='leasepartinquiry',
            name='vat_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.16'), max_digits=5),
        ),
    ]
