# Generated by Django 5.1.7 on 2025-09-09 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0026_alter_leaseaccinquiry_vat_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='store_acc_inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='bititec.storeaccessoryinquiry'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='store_part_inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='bititec.storepartinquiry'),
        ),
    ]
