# Generated by Django 5.1.7 on 2025-09-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0027_alter_sale_store_acc_inquiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stores',
            field=models.ManyToManyField(blank=True, help_text='Stores this user has access to', related_name='users', to='bititec.store'),
        ),
    ]
