# Generated by Django 5.1.7 on 2025-09-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0028_customuser_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='List of image URLs for this service call'),
        ),
    ]
