# Generated by Django 5.1.7 on 2025-10-17 17:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0030_sale_amount_paid_sale_due_date_sale_payment_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseServiceSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('Network Support', 'Network Support'), ('Hardware & Software Support', 'Hardware & Software Support'), ('Installation', 'Installation'), ('Scheduled Maintenance', 'Scheduled Maintenance')], max_length=50)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi-annual', 'Semi-Annual'), ('annual', 'Annual'), ('custom', 'Custom')], max_length=20)),
                ('frequency_months', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('lpo', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_technicians', models.ManyToManyField(blank=True, related_name='assigned_schedules', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_schedules', to='bititec.leasecontract')),
            ],
        ),
        migrations.AddField(
            model_name='call',
            name='lease_service_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_calls', to='bititec.leaseserviceschedule'),
        ),
    ]
