# Generated by Django 5.1.7 on 2025-10-17 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0031_leaseserviceschedule_call_lease_service_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='lease',
            field=models.ForeignKey(blank=True, help_text='Associated lease contract if this is a lease service call', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_calls', to='bititec.leasecontract'),
        ),
    ]
