# Generated by Django 5.1.7 on 2025-10-21 08:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0032_call_lease'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseMachineSwap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('swap_reason', models.TextField()),
                ('swapped_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_swaps', to='bititec.leasecontract')),
                ('new_machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='swapped_to_leases', to='bititec.machine')),
                ('old_machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='swapped_from_leases', to='bititec.machine')),
                ('swapped_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_swaps_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-swapped_at'],
            },
        ),
    ]
