# Generated by Django 5.1.7 on 2025-10-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0035_leasecontract_amount_paid_leasecontract_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leasecontract',
            name='technician',
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='monthly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
