# Generated by Django 5.1.7 on 2025-10-28 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0036_remove_leasecontract_technician_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasecontract',
            name='technician',
            field=models.ForeignKey(blank=True, help_text='Technician assigned for maintenance/support', limit_choices_to={'role__in': ['Technician', 'Technician Manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leases', to=settings.AUTH_USER_MODEL),
        ),
    ]
