# Generated by Django 5.1.7 on 2025-10-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0037_leasecontract_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='color_meter_reading',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='call',
            name='mono_meter_reading',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
