# Generated by Django 5.1.7 on 2025-10-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0038_call_color_meter_reading_call_mono_meter_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='color_meter_reading',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='mono_meter_reading',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
