# Generated by Django 5.1.7 on 2025-10-28 12:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0039_meterreading_color_meter_reading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyQPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('one_off', 'One-Off Payment'), ('subscription', 'Subscription')], default='subscription', max_length=20)),
                ('one_off_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('color_rate', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='MyQ rate per color copy (for color machines)', max_digits=10, null=True)),
                ('monochrome_rate', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='MyQ rate per monochrome copy', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myq_payments', to='bititec.leasecontract')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
