# Generated by Django 5.1.7 on 2025-10-28 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0040_myqpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leasecontract',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='leasecontract',
            name='initial_payment',
        ),
        migrations.RemoveField(
            model_name='leasecontract',
            name='monthly_rate',
        ),
        migrations.RemoveField(
            model_name='leasecontract',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='color_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rate per color copy (for color machines only)', max_digits=10),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='monochrome_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rate per monochrome/B&W copy', max_digits=10),
        ),
        migrations.AddField(
            model_name='leasepayment',
            name='meter_reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='bititec.meterreading'),
        ),
        migrations.AddField(
            model_name='leasepayment',
            name='payment_type',
            field=models.CharField(choices=[('monthly_bill', 'Monthly Bill'), ('myq_one_off', 'MyQ One-Off Payment')], default='monthly_bill', max_length=20),
        ),
    ]
