# Generated by Django 5.1.7 on 2025-10-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0041_remove_leasecontract_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasecontract',
            name='initial_color_counter',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Initial color counter reading when lease started (for used color machines)', null=True),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='initial_mono_counter',
            field=models.PositiveIntegerField(default=0, help_text='Initial monochrome counter reading when lease started (for used machines)'),
        ),
    ]
