# Generated by Django 5.1.7 on 2025-10-31 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0042_leasecontract_initial_color_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeaccessoryinquiry',
            name='lease',
            field=models.ForeignKey(blank=True, help_text='Associated lease for billing this accessory request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_accessory_inquiries', to='bititec.leasecontract'),
        ),
        migrations.AddField(
            model_name='storepartinquiry',
            name='lease',
            field=models.ForeignKey(blank=True, help_text='Associated lease for billing this part request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_part_inquiries', to='bititec.leasecontract'),
        ),
    ]
