# Generated by Django 5.1.7 on 2025-11-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bititec', '0044_add_qr_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='ref_no',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='serial_no',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='ref_no',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
