from django.conf import settings
from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from . import views
from .file_views import ChatFileUploadView
from django.conf.urls.static import static


urlpatterns = [
    path('users/', views.UserListCreate.as_view()),
    path('users/<uuid:id>/', views.UserRetrieveUpdateDestroy.as_view(), name='user-detail'),
    path('users/me/', views.current_user),
    path('register/', views.RegisterView.as_view()),
    path('change-password/', views.change_password),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'), 
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),  
    path('stores/', views.StoreListCreate.as_view()),
    path('stores/<uuid:id>/', views.StoreRetrieveUpdateDestroy.as_view()),
    path('accessory-types/', views.AccessoryTypeListCreate.as_view()),
    path('accessory-types/<uuid:pk>/', views.AccessoryTypeRetrieveUpdateDestroy.as_view()),
    path('machine-types/', views.MachineTypeListCreate.as_view()),
    path('machine-types/<uuid:pk>/', views.MachineTypeRetrieveUpdateDestroy.as_view()),
    path('part-types/', views.PartTypeListCreate.as_view()),
    path('part-types/<uuid:pk>/', views.PartTypeRetrieveUpdateDestroy.as_view()),
    path('machines/', views.MachineListCreate.as_view()),
    path('machines/<uuid:id>/', views.MachineRetrieveUpdateDestroy.as_view()),
    path('clients/', views.ClientListCreate.as_view()),
    path('clients/<uuid:id>/', views.ClientRetrieveUpdateDestroy.as_view()),
    path('accessories/', views.AccessoryListCreate.as_view()),
    path('accessories/<uuid:id>/', views.AccessoryRetrieveUpdateDestroy.as_view()),
    path('parts/', views.PartListCreate.as_view()),
    path('parts/<uuid:id>/', views.PartRetrieveUpdateDestroy.as_view()),
    path('service-calls/', views.CallViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('service-calls/<uuid:pk>/', views.CallViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'})),
    path('service-calls/<uuid:pk>/create_access_token/', views.CallViewSet.as_view({'post': 'create_access_token'}), name='create-access-token'),
    path('service-calls/validate_token/',  views.CallViewSet.as_view({'get': 'validate_token'}), name='validate-token'),
    path('service-calls/<uuid:pk>/verify/', views.CallViewSet.as_view({'post': 'verify'}), name='verify-call'),
    path('service-calls/<uuid:pk>/update_approval/', views.CallViewSet.as_view({'patch': 'update_approval'})),
    path('leases/', views.LeaseContractViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('leases/<uuid:pk>/', views.LeaseContractViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'})),
    path('sales/', views.SaleViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('sales/<uuid:pk>/', views.SaleViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('deliveries/', views.DeliveryViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('deliveries/<uuid:pk>/', views.DeliveryViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'})),
    path('deliveries/create_delivery/', views.DeliveryViewSet.as_view({'post': 'create_delivery'})),
    path('chat-groups/', views.ChatGroupViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('chat-groups/<uuid:pk>/', views.ChatGroupViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'})),
    path('chat-messages/', views.ChatMessageViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('chat-messages/<uuid:pk>/', views.ChatMessageViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'})),
    path('chat-messages/mark-as-read/', views.ChatMessageViewSet.as_view({'post': 'mark_as_read'})),
    path('chat/upload/', ChatFileUploadView.as_view(), name='chat-file-upload'),
    path('chat-groups/<uuid:pk>/messages/', views.ChatGroupViewSet.as_view({'get': 'messages'})),
    path('chat-groups/<uuid:pk>/mark_read/', views.ChatGroupViewSet.as_view({'post': 'mark_read'})),
    path('chat-groups/global/', views.ChatGroupViewSet.as_view({'get': 'global_chat'})),
    path('lease-part-inquiries/', views.LeasePartInquiryViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('lease-part-inquiries/<uuid:pk>/', views.LeasePartInquiryViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'})),
    path('lease-acc-inquiries/', views.LeaseAccInquiryViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('lease-acc-inquiries/<uuid:pk>/', views.LeaseAccInquiryViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'})),
    path('meter-readings/', views.MeterReadingViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('meter-readings/<uuid:pk>/', views.MeterReadingViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'})),
    path('leases/<uuid:pk>/meter-readings/', views.LeaseContractViewSet.as_view({'get': 'meter_readings'})),
    path('store-inquiries/', views.StoreInquiryViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('store-inquiries/<uuid:pk>/', views.StoreInquiryViewSet.as_view({'get': 'retrieve', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('client-machines/', views.ClientMachineViewSet.as_view({'get': 'list', 'post': 'create'})),
]