from django.conf import settings
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from . import views
from .file_views import ChatFileUploadView
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter

urlpatterns = [
    path('users/', views.UserListCreate.as_view()),
    path('users/<uuid:id>/', views.UserRetrieveUpdateDestroy.as_view(), name='user-detail'),
    path('users/me/', views.current_user),
    path('register/', views.RegisterView.as_view()),
    path('change-password/', views.change_password),
    path('get-salt/', views.get_salt, name='get_salt'),
    path('token/', views.SecureTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('session/validate/', views.validate_session, name='validate_session'),  
    path('unlock-account/', views.unlock_account, name='unlock_account'),
    path('grant_key_access/', views.grant_key_access, name='grant_key_access'),
    path('revoke_key_access/', views.revoke_key_access, name='revoke_key_access'),
    path('permission-audit/<uuid:user_id>/', views.get_key_audit, name='get_key_audit'),
    path('stores/', views.StoreListCreate.as_view()),
    path('stores/<uuid:id>/', views.StoreRetrieveUpdateDestroy.as_view()),
    path('user-stores/', views.UserStoreListView.as_view(), name='user-stores'),
    path('accessory-types/', views.AccessoryTypeListCreate.as_view()),
    path('accessory-types/<int:pk>/', views.AccessoryTypeRetrieveUpdateDestroy.as_view()),
    path('machine-types/', views.MachineTypeListCreate.as_view()),
    path('machine-types/<int:pk>/', views.MachineTypeRetrieveUpdateDestroy.as_view()),
    path('part-types/', views.PartTypeListCreate.as_view()),
    path('part-types/<int:pk>/', views.PartTypeRetrieveUpdateDestroy.as_view()),
    path('machines/', views.MachineListCreate.as_view()),
    path('machines/<uuid:id>/', views.MachineRetrieveUpdateDestroy.as_view()),
    path('clients/', views.ClientListCreate.as_view()),
    path('clients/<uuid:id>/', views.ClientRetrieveUpdateDestroy.as_view()),
    path('accessories/', views.AccessoryListCreate.as_view()),
    path('accessories/<uuid:id>/', views.AccessoryRetrieveUpdateDestroy.as_view()),
    path('parts/', views.PartListCreate.as_view()),
    path('parts/<uuid:id>/', views.PartRetrieveUpdateDestroy.as_view()),
    path('service-calls/', views.CallViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('service-calls/<uuid:pk>/', views.CallViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'})),
    path('service-calls/<uuid:pk>/create_access_token/', views.CallViewSet.as_view({'post': 'create_access_token'})),
    path('service-calls/validate_token/', views.CallValidateTokenView.as_view(), name='validate-token'),
    path('service-calls/<uuid:pk>/verify/', views.CallVerifyTokenView.as_view(), name='verify-call'),
    path('service-calls/<uuid:pk>/update_approval/', views.CallViewSet.as_view({'patch': 'update_approval'})),
    path('service-calls/<uuid:pk>/start_service/', views.CallViewSet.as_view({'post': 'start_service'})),
    path('service-calls/<uuid:pk>/complete_service/', views.CallViewSet.as_view({'post': 'complete_service'})),
    path('service-calls/<uuid:pk>/upload-images/', views.CallViewSet.as_view({'post': 'upload_images'})),
    path('service-calls/<uuid:pk>/remove-image/', views.CallViewSet.as_view({'delete': 'remove_image'})),
    path('leases/', views.LeaseContractViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('leases/<uuid:pk>/', views.LeaseContractViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'update', 'delete': 'destroy'})),
    path('leases/<uuid:pk>/terminate_lease/', views.LeaseContractViewSet.as_view({'patch': 'terminate_lease'})),
    path('leases/<uuid:pk>/reinstate_lease/', views.LeaseContractViewSet.as_view({'patch': 'reinstate_lease'})),
    path('leases/<uuid:pk>/assign-account-handler/', views.LeaseContractViewSet.as_view({'patch': 'assign_account_handler'})),
    path('leases/assign-technician/', views.LeaseAssignTechnician.as_view(), name='assign-technician'),
    # path('leases/my-handled-leases/', views.LeaseContractViewSet.as_view({'get': 'my_handled_leases'})),
    path('leases/assign-account-handler/', views.LeaseAssignAccountHandler.as_view(), name='bulk-assign-account-handler'),
    path('lease-service-schedules/', views.LeaseServiceScheduleViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('lease-service-schedules/<uuid:pk>/', views.LeaseServiceScheduleViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('lease-service-schedules/<uuid:pk>/generate_calls/', views.LeaseServiceScheduleViewSet.as_view({'post': 'generate_calls'})),
    path('lease-machine-swaps/', views.LeaseMachineSwapViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('payments/', views.PaymentViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('payments/<uuid:pk>/', views.PaymentViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('sales/', views.SaleViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('sales/<uuid:pk>/', views.SaleViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('sales/<uuid:pk>/payments/', views.SaleViewSet.as_view({'get': 'payments'})),
    path('sales/<uuid:pk>/add_payment/', views.SaleViewSet.as_view({'post': 'add_payment'})),
    path('quotations/', views.QuotationViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('quotations/<uuid:pk>/', views.QuotationViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'})),
    path('quotations/<uuid:pk>/pdf/', views.QuotationPDFView.as_view(), name='quotation-pdf'),
    path('deliveries/', views.DeliveryViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('deliveries/<uuid:pk>/', views.DeliveryViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'})),
    path('deliveries/create_delivery/', views.DeliveryViewSet.as_view({'post': 'create_delivery'})),
    path('chat-groups/', views.ChatGroupViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('chat-groups/<uuid:pk>/', views.ChatGroupViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'})),
    path('chat-messages/', views.ChatMessageViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('chat-messages/<uuid:pk>/', views.ChatMessageViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'})),
    path('chat-messages/mark-as-read/', views.ChatMessageViewSet.as_view({'post': 'mark_as_read'})),
    path('chat/upload/', ChatFileUploadView.as_view(), name='chat-file-upload'),
    path('chat-groups/<uuid:pk>/messages/', views.ChatGroupViewSet.as_view({'get': 'messages'})),
    path('chat-groups/<uuid:pk>/mark_read/', views.ChatGroupViewSet.as_view({'post': 'mark_read'})),
    path('chat-groups/global/', views.ChatGroupViewSet.as_view({'get': 'global_chat'})),
    path('lease-part-inquiries/', views.LeasePartInquiryViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('lease-part-inquiries/<uuid:pk>/', views.LeasePartInquiryViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'update', 'delete': 'destroy'})),
    path('lease-acc-inquiries/', views.LeaseAccInquiryViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('lease-acc-inquiries/<uuid:pk>/', views.LeaseAccInquiryViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'update', 'delete': 'destroy'})),
    path('meter-readings/', views.MeterReadingViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('meter-readings/<uuid:pk>/', views.MeterReadingViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'})),
    path('leases/<uuid:pk>/meter-readings/', views.LeaseContractViewSet.as_view({'get': 'meter_readings'})),
    path('store-part-inquiries/', views.StorePartInquiryViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('store-part-inquiries/<uuid:pk>/', views.StorePartInquiryViewSet.as_view({'get': 'retrieve', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('store-acc-inquiries/', views.StoreAccessoryInquiryViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('store-acc-inquiries/<uuid:pk>/', views.StoreAccessoryInquiryViewSet.as_view({'get': 'retrieve', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('client-machines/', views.ClientMachineViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('transfers/', views.TransferListCreate.as_view(), name='transfer-list'),
    path('transfers/<uuid:pk>/', views.TransferRetrieveUpdateDestroy.as_view(), name='transfer-detail'),
    path('transfers/<uuid:pk>/complete/', views.CompleteTransferView.as_view(), name='complete-transfer'),
    path('machines/<uuid:machine_id>/parts/<uuid:part_id>/remove/',  views.PartMovementView.as_view(), name='remove-part'),
    path('machines/<uuid:machine_id>/parts/<uuid:part_id>/install/', views.PartInstallationView.as_view(), name='install-part'),
    path('purchase-orders/', views.PurchaseOrderViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('purchase-orders/<uuid:pk>/', views.PurchaseOrderViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'})),
    path('purchase-orders/<uuid:pk>/submit/', views.PurchaseOrderViewSet.as_view({'post': 'submit_for_approval'})),
    path('purchase-orders/<uuid:pk>/verify/', views.PurchaseOrderViewSet.as_view({'post': 'verify'})),
    path('purchase-orders/<uuid:pk>/pdf/', views.PurchaseOrderPDFView.as_view(), name='purchase-order-pdf'),
    path('health/', views.mobile_health_check, name='health_check'),
    path('device/register/', views.mobile_device_info, name='device_register'),
    path('test/', views.simple_test, name='simple_test'),
    path('api/test/', views.simple_test, name='api_test'),
]